### ISSUE TITLE
fednode_run.py fails to find pytest, even when it is already installed?

### ISSUE THREAD

**Issue by curtislacy** [CounterpartyXCP/federatednode_build#211] opened 2015-02-09 19:48 UTC
I've got pytest installed, as near as I can tell:
```
bitcoin@xcpapi-2015-2-9:~$ sudo pip3 install pytest
Requirement already satisfied (use --upgrade to upgrade): pytest in /usr/local/lib/python3.4/dist-packages
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.25 in /usr/local/lib/python3.4/dist-packages (from pytest)
Cleaning up...
bitcoin@xcpapi-2015-2-9:~$ sudo pip install pytest
Requirement already satisfied (use --upgrade to upgrade): pytest in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.19 in /usr/local/lib/python2.7/dist-packages (from pytest)
Cleaning up...
bitcoin@xcpapi-2015-2-9:~$ 
```
However, when I run ```sudo python3 /tmp/fednode_run.py``` it fails (here's the end of the log file):
```
Running pytest-cov-1.8.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3x44401z/pytest-cov-1.8.1/egg-dist-tmp-yihq49ii

pytest-cov 1.8.1 is already the active version in easy-install.pth



Installed /home/xcp/federatednode_build/env/lib/python3.4/site-packages/pytest_cov-1.8.1-py3.4.egg

error: Could not find required distribution pytest

----------------------------------------
Cleaning up...
  Removing temporary dir /home/xcp/federatednode_build/env/build...
Command /home/xcp/federatednode_build/env/bin/python3.4 -c "import setuptools, tokenize;__file__='/home/xcp/federatednode_build/env/build/counterpartylib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-iael3j49-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/xcp/federatednode_build/env/include/site/python3.4 failed with error code 1 in /home/xcp/federatednode_build/env/build/counterpartylib
Exception information:
Traceback (most recent call last):
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command /home/xcp/federatednode_build/env/bin/python3.4 -c "import setuptools, tokenize;__file__='/home/xcp/federatednode_build/env/build/counterpartylib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-iael3j49-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/xcp/federatednode_build/env/include/site/python3.4 failed with error code 1 in /home/xcp/federatednode_build/env/build/counterpartylib
```

**Comment by rippler** [comment] 2015-02-10 04:17
I haven't seen this one and I tried the current develop branch of Fed Node Build Scripts several times, last time 9 hours ago.

I see these similar errors pop up every now and then due to HTTP/DNS timeouts. I'd try one more time just to eliminate that possibility.

**Comment by rippler** [comment] 2015-02-10 12:35
I tried again, pulled Fed Node script from `develop`, installed everything (Counterwallet, testnet & mainnet) from `master`. Did not encounter this problem.

**Comment by robby-dermody** [comment] 2015-02-11 16:07
closing as I can't reproduce it either, please reopen if you can provide instructions to reproduce

**Closed by robby-dermody** 2015-02-11 16:07 UTC
